const gallery = [
{
  id: 1,
  title: 'Table Lamp',
  description: 'photo of a table lamp',
  imageSrc: 'https://unsplash.com/photos/sTo3IYhYC_c',
  width:'450',
  height:'300',
  category:'Lighting',
},
{
  id: 2,
  title: 'Floor Lamp',
  description: 'Photo of a floor lamp',
  imageSrc: 'https://unsplash.com/photos/JIUjvqe2ZHg',
  width:'450',
  height:'300',
  category: 'Lighting',
},
{
  id: 3,
  title: 'Hanging Lamp',
  description: 'photo of a hanging lamp',
  imageSrc:'https://unsplash.com/photos/YfuqJiiYVjc',
  width: '450',
  height:'300',
  category:'Lighting',
},
{
  id: 4,
  title: 'Samsung Small TV',
  description: 'photo of a small samsung tv',
  imageSrc:'https://unsplash.com/photos/kfOsD43Pkx4',
  width:'450',
  height:'300',
  category: 'TV',
},
{
  id: 5,
  title: 'Samsung Medium TV',
  description: 'photo of a medium tv',
  imageSrc:'https://unsplash.com/photos/fg00hP0VPI8',
  width:'450',
  height:'300',
  category: 'TV',
},
{
  id: 6,
  title: 'Samsung Large TV',
  description: 'photo of large tv',
  imageSrc:'https://pixabay.com/photos/tv-set-tv-television-screen-cinema-4308538/',
  width:'450',
  height:'300',
  category: 'TV',
},
{
  id: 7,
  title: 'Vegan Leather Sofa'  ,
  description: 'Photo of Vegan Leather Sofa beside the window' ,
  imageSrc:'https://unsplash.com/photos/7XOYJHppytw',
  width:'450',
  height:'300',
  category: 'Sofa',
},
{
  id: 8,
  title: 'Fabric Sofa',
  description:'Photo of Fabric sofa with a cat on it',
  imageSrc:'https://unsplash.com/photos/FBXuXp57eM0',
  width:'450',
  height:'300',
  category: 'Sofa',
},
{
  id: 9,
  title: 'Leather Sofa',
  description:'Photo of Leather sofa',
  imageSrc:'https://unsplash.com/photos/nWidMEQsnAQ',
  width:'450',
  height:'300',
  category: 'Sofa',
},
{
  id: 10,
  title:'Round Oak Table',
  description:'photo of a round oak table',
  imageSrc: 'https://unsplash.com/photos/jc9dkaaEYr4',
  width:'450',
  height:'300',
  category: 'coffee table',
},
{
  id: 11,
  title: 'Cherry Coffee Table',
  description: 'photo of a cherry coffee table with a laptop',
  imageSrc: 'https://unsplash.com/photos/JB27lNW9AlM',
  width:'450',
  height:'300',
  category: 'coffee table',
},
{
  id: 12,
  title: 'Pine Coffee Table',
  description: 'photo of a pine coffee table',
  imageSrc:'https://unsplash.com/photos/77cctx2YdM4',
  width:'450',
  height:'300',
  category: 'coffee table',
}
]

module.exports = gallery;