const gallery = [
{
  id: 1,
  title: 'Table Lamp',
  description: 'photo of a table lamp',
  imageSrc:,
  width:,
  height:,
  category:'Lighting',
},
{
  id: 2,
  title: 'Floor Lamp',
  description: 'Photo of a floor lamp',
  imageSrc:,
  width:,
  height:,
  category: 'Lighting',
},
{
  id: 3,
  title: 'Hanging Lamp',
  description: 'photo of a hanging lamp',
  imageSrc:,
  width:,
  height:,
  category:'Lighting',
},
{
  id: 4,
  title: 'Samsung Small TV',
  description: 'photo of a small samsung tv',
  imageSrc:,
  width:,
  height:,
  category: 'TV',
},
{
  id: 5,
  title: 'Samsung Medium TV',
  description: 'photo of a medium tv',
  imageSrc:,
  width:,
  height:,
  category: 'TV',
},
{
  id: 6,
  title: 'Samsung Large TV',
  description: 'photo of large tv',
  imageSrc:,
  width:,
  height:,
  category: 'TV',
},
{
  id: 7,
  title: ,
  description: ,
  imageSrc:,
  width:,
  height:,
  category: 'Sofa',
},
{
  id: 8,
  title:,
  description:,
  imageSrc:,
  width:,
  height:,
  category: 'Sofa',
},
{
  id: 9,
  title:,
  description:,
  imageSrc:,
  width:,
  height:,
  category: 'Sofa',
},
{
  id: 10,
  title:'Round Oak Table',
  description:'photo of a round oak table',
  imageSrc:,
  width:,
  height:,
  category: 'coffee table',
},
{
  id: 11,
  title: 'Cherry Coffee Table',
  description: 'photo of a cherry coffee table with a laptop',
  imageSrc:,
  width:,
  height:,
  category: 'coffee table',
},
{
  id: 12,
  title: 'Pine Coffee Table',
  description: 'photo of a pine coffee table',
  imageSrc:,
  width:,
  height:,
  category: 'coffee table',
}]